behaviors:
  MoveToGoal:
  
    trainer_type: ppo

    hyperparameters:
      batch_size: 2048
      buffer_size: 10240
      learning_rate: 3.0e-5
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: linear

    network_settings:
      normalize: true
      hidden_units: 264
      num_layers: 3

    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 0.99
      gail:
        strength: 0.3
        demo_path: Demos/IWillShowU_0.demo
        use_actions: false

    behavioral_cloning: 
      demo_path: Demos/IWillShowU_0.demo
      steps: 750000
      strength: 0.4

    keep_checkpoints: 15
    checkpoint_interval: 1000000
    time_horizon: 1024
    max_steps: 500000000
    summary_freq: 100000
    threaded: true