behaviors:
  MoveToGoal:
  
    trainer_type: sac

    hyperparameters:
      batch_size: 128
      buffer_size: 50000
      learning_rate: 3.0e-5
      buffer_init_steps: 5000
      init_entcoef: 1
      save_replay_buffer: false
      tau: 0.005
      steps_per_update: 1
      learning_rate_schedule: constant

    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 3

    reward_signals:
      extrinsic:
        gamma: 0.75
        strength: 0.99
      gail:
        strength: 0.3
        demo_path: Demos/IWillShowU_0.demo
        use_actions: false

    behavioral_cloning: 
      demo_path: Demos/IWillShowU_0.demo
      steps: 750000
      strength: 0.4

    keep_checkpoints: 15
    checkpoint_interval: 1000000
    time_horizon: 264
    max_steps: 500000000
    summary_freq: 20000
    threaded: true